### ISSUE TITLE
module' object has no attribute 'Acapela'

### ISSUE THREAD

**Issue by pxg** [newfies-dialer/python-acapela#1]
When I try and run example.py I get the error:

Traceback (most recent call last):
  File "acapela.py", line 79, in <module>
    test_acapela()
  File "acapela.py", line 42, in test_acapela
    tts_acapela = acapela.Acapela(ACCOUNT_LOGIN, APPLICATION_LOGIN, APPLICATION_PASSWORD, SERVICE_URL, QUALITY, DIRECTORY)
AttributeError: 'module' object has no attribute 'Acapela'

**Comment by pxg** [comment]
Unable to replicate this bug.

**Comment by edelpech** [comment]
Hi, 
I just got the same problem. Any idea ?

**Comment by areski** [comment]
This might depend of your import

> import acapela
> as you can see there:
> https://github.com/areski/python-acapela/blob/master/acapela.py#L81
> There is a Class Acapela

**Comment by edelpech** [comment]
Ok thanks. I've directly used acapela.py. It's working fine now.
Thx
