### ISSUE TITLE
Acapela attach strange information before the given text

### ISSUE THREAD

**Issue by rastaxe** [newfies-dialer/python-acapela#2]
Hi! I used the python script for a while without a problem, but today the generated audio has some strange number before the given text. The generated audio says something like VCT=100s PD=160 and then it says the correct given text.
Can you confirm that?

**Comment by rastaxe** [comment]
That was a problem on the vaas server. Now it is solved.

**Comment by areski** [comment]
I close the ticket if nothing need to be changed then
