### ISSUE TITLE
Problem during the downloading of the generated mp3 file

### ISSUE THREAD

**Issue by rastaxe** [newfies-dialer/python-acapela#3]
I have problems with the generated mp3 file. It is too short and it is not a valid mp3 file.
Are you experiencing the same issue?
Best regards!

**Comment by areski** [comment]
Very short file may mean you have an issue with the API, try to open the mp3 in a text editor

**Comment by rastaxe** [comment]
In the mp3 it is written: "err_code=INVALID_PARAM_ERROR&err_msg=errors as id3 tags is not supported anymore, please check http code return instead".
I used the python-acapela package some months ago without problems. Now I have this error and I do not know how to solve it. Can you help me?

**Comment by areski** [comment]
Solved with this commit https://github.com/areski/python-acapela/commit/ba5d60b0ef589edb275631e6282a3e45f8d5c9f9
